### ISSUE TITLE
ENOENT running ionic serve

### ISSUE THREAD

**Issue by milseg** [castrolol/ng2-mask-money#30]
Module build failed: Error: ENOENT: no such file or directory, open 'node_modules\ng2-money-mask\index.js.map'

Error: Module build failed: Error: ENOENT: no such file or directory, open 'C:\Users\prfjb\Documents\Workspaces\Inquilinno\inquilinnoProprietarioApp\node_modules\ng2-money-mask\index.js.map'
    at Object.<anonymous> (http://localhost:8100/build/vendor.js:132698:7)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.234 (http://localhost:8100/build/main.js:1285:74)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.210 (http://localhost:8100/build/main.js:1234:70)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at webpackJsonpCallback (http://localhost:8100/build/vendor.js:26:23)
    at http://localhost:8100/build/main.js:1:1

Ionic Framework: 3.9.2
Ionic App Scripts: 3.1.8
Angular Core: 5.0.3
Angular Compiler CLI: 5.0.3
Node: 8.9.4
OS Platform: Windows 10
Navigator Platform: Win32
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36

**Comment by rodolfocop** [comment]
Hi, it's not working right now for IONIC.

**Comment by rodolfocop** [comment]
you can try to use the new version to see if the problem has been solved.
